insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (1, 'Matty', '786-4937032', 'Internal Medicine', 2, 51);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (2, 'Tobias', '098-9965137', 'Dermatology', 2, 52);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (3, 'Sayre', '427-9877208', 'Cardiology', 5, 53);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (4, 'Kean', '305-0502220', 'Orthopedics', 9, 54);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (5, 'Arley', '183-8827874', 'Internal Medicine', 4, 55);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (6, 'Aymer', '168-5068628', 'Cardiology', 7, 56);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (7, 'Derick', '726-1762635', 'Dermatology', 3, 57);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (8, 'Gale', '783-1602654', 'Internal Medicine', 9, 58);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (9, 'Duff', '826-3709310', 'Cardiology', 10, 59);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (10, 'Harley', '335-1932563', 'Neurology', 1, 60);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (11, 'Claus', '348-6490213', 'Neurology', 4, 61);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (12, 'Quinton', '167-8162012', 'Neurology', 1, 62);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (13, 'Chariot', '383-9687935', 'Internal Medicine', 2, 63);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (14, 'Cyrillus', '441-6548298', 'Orthopedics', 1, 64);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (15, 'Leeland', '924-0413864', 'Neurology', 4, 65);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (16, 'Richmound', '161-1844168', 'Dermatology', 3, 66);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (17, 'Forester', '814-3170201', 'Dermatology', 9, 67);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (18, 'Alec', '989-2252954', 'Orthopedics', 9, 68);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (19, 'Tomas', '115-4454484', 'Internal Medicine', 5, 69);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (20, 'Murry', '096-4096385', 'Dermatology', 6, 70);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (21, 'Rodney', '511-7441895', 'Dermatology', 7, 71);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (22, 'Huntlee', '070-9174704', 'Dermatology', 8, 72);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (23, 'Garwin', '479-9784448', 'Neurology', 7, 73);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (24, 'Hillie', '663-2811968', 'Dermatology', 4, 74);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (25, 'Eugen', '840-6806824', 'Internal Medicine', 3, 75);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (26, 'Evelin', '956-4219883', 'Neurology', 3, 76);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (27, 'Nikolaos', '149-6379194', 'Dermatology', 6, 77);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (28, 'Delainey', '643-8027560', 'Neurology', 4, 78);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (29, 'Kennie', '533-1722920', 'Cardiology', 9, 79);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (30, 'Aubert', '592-1315095', 'Orthopedics', 6, 80);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (31, 'Wilfred', '206-0954248', 'Neurology', 4, 81);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (32, 'Barnett', '264-8633822', 'Internal Medicine', 2, 82);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (33, 'Carter', '036-7112916', 'Cardiology', 5, 83);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (34, 'Trip', '828-9430171', 'Neurology', 10, 84);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (35, 'Connor', '145-4963758', 'Neurology', 4, 85);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (36, 'Sandor', '053-0150546', 'Orthopedics', 8, 86);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (37, 'Jamil', '196-4198761', 'Neurology', 4, 87);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (38, 'Nevin', '488-1406931', 'Neurology', 4, 88);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (39, 'Krisha', '978-8818648', 'Orthopedics', 7, 89);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (40, 'Randi', '140-0041324', 'Neurology', 5, 90);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (41, 'Ragnar', '606-6421110', 'Neurology', 7, 91);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (42, 'Granville', '516-3450505', 'Cardiology', 7, 92);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (43, 'Benito', '082-0560623', 'Cardiology', 8, 93);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (44, 'Timmie', '837-4438734', 'Dermatology', 10, 94);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (45, 'Hercule', '990-3217036', 'Internal Medicine', 6, 95);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (46, 'Axe', '846-7648941', 'Orthopedics', 9, 96);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (47, 'Benjie', '691-2106273', 'Dermatology', 7, 97);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (48, 'Currey', '548-3950995', 'Dermatology', 7, 98);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (49, 'Reinhard', '059-7365175', 'Dermatology', 3, 99);
insert into Doctors (DoctorID, DName, DTelephoneNo, Specialization, DepartmentID, AccountID) values (50, 'Haley', '043-3531307', 'Cardiology', 6, 100);
